### PR TITLE
Fix #4599 - PR Checker build failing

### LINKED ISSUE #4599: PR Checker build failing
### Describe the bug

Pr Checker workflow is failing for some tests and overlogging CSS errors from JSDOM

### Reproducer

Pr Checker

### PrimeVue version

3.36.1-SNAPSHOT

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by FlipWarthog**
Fix #4599 - PR Checker build failing

Creating as a draft to test the workflows

### CODE REVIEW

**Comment by FlipWarthog** [comment]
@mertsincan I stole your comment from #4512 and included it in the main vitest config.

File: components/lib/splitbutton/SplitButton.vue [hunk 1]
```diff
@@ -80,7 +80,10 @@ export default {
     },
     methods: {
         onDropdownButtonClick(event) {
-            event.preventDefault();
+            if (event) {
+                event.preventDefault();
+            }
```
Comment (FlipWarthog) [inline components/lib/splitbutton/SplitButton.vue:85]: Test was failing with event undefined due to the call on line 92.

File: components/lib/button/Button.spec.js [hunk 2]
```diff
@@ -79,6 +79,6 @@ describe('Button.vue', () => {
             }
         });
 
-        expect(wrapper.html()).toBe(`<button class="p-button p-component" type="button" data-pc-name="button" data-pc-section="root" data-pd-ripple="true"><span class="ml-2 font-bold">Default PrimeVue Button</span></button>`);
+        expect(wrapper.html()).toBe(`<button class="p-button p-component" type="button" data-pc-name="button" data-pc-section="root"><span class="ml-2 font-bold">Default PrimeVue Button</span></button>`);
```
Comment (FlipWarthog) [inline components/lib/button/Button.spec.js:82]: Still investigating this. I think it's just a ripple config change?

File: components/lib/rating/Rating.spec.js [hunk 3]
```diff
@@ -37,7 +37,7 @@ describe('Rating.vue', () => {
     it('When star is clicked, onOptionClick method should triggered', async () => {
         await wrapper.find('.p-rating-item').trigger('click');
 
-        expect(wrapper.find('.p-focus').exists()).toBe(true);
+        expect(wrapper.find('[data-p-focused="true"]').exists()).toBe(true);
```
Comment (FlipWarthog) [inline components/lib/rating/Rating.spec.js:40]: `p-focus` is not added on click, just keyboard nav, so looking for the data attribute instead.

File: components/lib/button/Button.spec.js (hunk 2 above)
Comment (FlipWarthog) [reply components/lib/button/Button.spec.js:82]: Investigated, `ripple` is disabled in the default configs which the tests are using so this is a correct assert.
