### PR TITLE
Fix #5008  InputNumber: Cleanup KeyDown

### LINKED ISSUE #5008: InputNumber: Bug deprecated KeyCode Usage
### Describe the bug

# Bug Summary

The current implementation of the onInputKeyPress method in the InputNumber component of PrimeVue relies on the deprecated keyCode property, which is set to be removed in future browser versions. This poses a potential risk of unsupported behavior as modern libraries and tools may cease to support this deprecated property.

## Issue Details

The usage of keyCode is deprecated and marked for removal, causing compatibility issues with modern libraries and testing tools. For instance, the testing library (testing-library/user-event) no longer supports keyCode, as highlighted in this related issue: [testing-library/user-event#842](https://github.com/testing-library/user-event/issues/842). When attempting to test the InputNumber component using this library, the keyCode remains 0, and no event is emitted.

### Reproducer

https://codesandbox.io/p/devbox/wizardly-framework-5vw3dy?file=%2Fsrc%2FApp.vue%3A15%2C10

### PrimeVue version

3.45.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #5008 

@tugcekucukoglu this cleans up the InputNumber keydown to match PrimeReact.

1. Removed `console.log`
2. Moved all short circuits to the top of the method that `return`
3. Removed unreachable check for `altKey`

### CODE REVIEW

File: components/lib/inputnumber/InputNumber.vue [hunk 1]
```diff
@@ -376,23 +376,19 @@ export default {
...
+
             let selectionStart = event.target.selectionStart;
             let selectionEnd = event.target.selectionEnd;
             let inputValue = event.target.value;
             let newValueStr = null;
 
-            if (event.altKey) {
-                event.preventDefault();
-            }
-
```
Comment (melloware) [inline components/lib/inputnumber/InputNumber.vue:395]: This event.altKey was unreachable based on the short circuit above.

**Review by tugcekucukoglu — APPROVED** [review]
