### PR TITLE
fix: Fixes input trigger on right mouse click

### LINKED ISSUE #4144: File Upload - Chrome/Windows input is triggered during any mouse click, not just left click
### Describe the bug

The File dialog for FileUpload is triggered via any interaction with the mouse on windows devices - not only left click but also right click and middle click. In the following animation I always only use right and middle click
click

Happens only on Windows + Chrome, not Firefox, Edge, Vivaldi or other browsers.

### Reproducer

https://codesandbox.io/s/hnxc5y

### PrimeVue version

3.30.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 114

### Steps to reproduce the behavior

Go to https://primevue.org/fileupload/ right click on the first FileUpload -> see it opens the file browser and closes the context menu directly

### Expected behavior

Only the context menu should open

### PR DESCRIPTION
**Pull request by navedqb**
Fixes #4144

### CODE REVIEW

File: components/lib/fileupload/FileUpload.vue [hunk 1]
```diff
@@ -293,9 +293,11 @@ export default {
                 }
             }
         },
-        onBasicUploaderClick() {
+        onBasicUploaderClick(event) {
             if (this.hasFiles) this.upload();
-            else this.$refs.fileInput.click();
+            else if (event.button === 0) {
```
Comment (SoyDiego) [inline components/lib/fileupload/FileUpload.vue:298]: Instead `else if` maybe another `if` it's cleaner in my opinion.

```
 if (this.hasFiles) this.upload();
 if (event.button === 0) this.$refs.fileInput.click();
```

**Review by SoyDiego — APPROVED** [review]

**Comment by mertsincan** [comment]
Thanks a lot for your contribution!
